import React from 'react';
import Image from 'next/image';
export const metadata = {
    title: "About us",
    description: "Generated by create next app",
  };
  
const AboutPage = () => {
    return (
        <div>
           <h2>about</h2> 

           <Image src="https://i.ibb.co.com/gLdb4f4K/mustafa.png" width={300} height="300" alt='maaraa kha'></Image>
           <Image src="https://images.unsplash.com/photo-1789283170426-1d1305571e26" width={300} height="300" alt='maaraa kha'></Image>
           <Image src="/mustafa.png" width={300} height="300" alt='maaraa kha'></Image>
           <Image src="/images/gary.png" height="400" width={400} alt='oi kire'></Image>
        </div>
    );
};

export default AboutPage;